name: secure_vault_shell
description: Flutter shell for the secure vault explorer.
publish_to: "none"
version: 0.3.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  cryptography: ^2.9.0
  crypto: ^3.0.7
  archive: ^4.0.9
  xml: 6.5.0
  syncfusion_flutter_pdf: ^33.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
