name: secure_vault_shell
description: Flutter shell for the secure vault explorer.
publish_to: "none"
version: 0.12.3

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  cryptography: ^2.9.0
  crypto: ^3.0.7
  archive: ^4.0.9
  xml: 6.5.0
  syncfusion_flutter_pdf: ^33.2.8
  image: ^4.5.4
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_android_video: ^1.3.8
  dartssh2: ^2.17.1
  dart_smb2: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/icons/logo_program.png
